# Numpy Tutorials

Numpy is a general purpose array-processing package. It porvides a high performance multidimensional aray object and tools for working with these arrays

In [1]:
## first we import numpy
import numpy as np

In [2]:
my_lst = [1,2,3,4]
arr = np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(4,)

In [7]:
#create a 2-d array
my_lst1 = [1,2,3,4]
my_lst2 = [4,5,6,7]
my_lst3 = [7,8,9,10]
arr=np.array([my_lst1, my_lst2, my_lst3])

In [8]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [9]:
arr.shape

(3, 4)

In [10]:
arr.reshape(4,3) #reshaped but not saved to arr

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [11]:
arr.shape #arr back to its originl form

(3, 4)

In [12]:
print(arr)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


# Indexing in Numpy - Arrays

In [13]:
arr[2]

array([ 7,  8,  9, 10])

In [14]:
arr[0:,:]

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [16]:
arr[1:,2:]

array([[ 6,  7],
       [ 9, 10]])

In [22]:
newArr = np.arange(1,10, step = 2)
print(newArr)

[1 3 5 7 9]


In [23]:
arr1 = newArr.copy()

In [24]:
print(arr1)

[1 3 5 7 9]


In [26]:
# some conditions for Exploratory Data Analysis

val = 200
arr[arr<val]

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

In [27]:
arr*2

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14],
       [14, 16, 18, 20]])

In [28]:
np.ones(4)
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
#random distribution

np.random.rand(3,3)

array([[0.99439912, 0.6593272 , 0.33560557],
       [0.56791916, 0.54516676, 0.93142335],
       [0.79180048, 0.12629603, 0.81877894]])

In [31]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
np.random.randint(0,100, 8 ).reshape(2,4)  #random 8 integer values from 0 - 100

array([[54, 30, 28, 48],
       [34, 46, 86, 60]])

# Pandas 
Pandas is an open source library, high-perfromance, easy to use data analysis tool

 - What is data frames
 - what is data series 
 - Different operation in Pandas

In [2]:
pip install pandas

     ---------------------------------------- 10.9/10.9 MB 6.1 MB/s eta 0:00:00
     -------------------------------------- 498.1/498.1 KB 7.9 MB/s eta 0:00:00
     ---------------------------------------- 14.7/14.7 MB 5.8 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
Note: you may need to restart the kernel to use updated packages.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.5.0 requires numpy~=1.19.2, but you have numpy 1.23.5 which is incompatible.
tensorflow-gpu 2.5.0 requires numpy~=1.19.2, but you have numpy 1.23.5 which is incompatible.
You should consider upgrading via the 'C:\Users\DELL\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [3]:
# first step to import pandas
import pandas as pd
import numpy as np

In [6]:
# creating dataframe

df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Row1','Row2','Row3','Row4','Row5'], columns = ['column1','column2', 'column3','column4'])

In [7]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [8]:
df.to_csv('Test1.csv') #convert dataframe to csv

In [15]:
# Accessing the elements of Row1

df.loc['Row1']

type(df.loc['Row1']) #series is one row or one column 

column1    0
column2    1
column3    2
column4    3
Name: Row1, dtype: int32

In [25]:
df['column1'] #print values of a specific column

# df[['column1','column2']]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: column1, dtype: int32

In [16]:
#iloc for specific data frame

df.iloc[:,1:]

column2  column3  column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [17]:
#convert dataframe to arrays

df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [18]:
df['column1'].value_counts() #finds unique categories

0     1
4     1
8     1
12    1
16    1
Name: column1, dtype: int64

In [19]:
df.isnull().sum() #checks for null values in a column

column1    0
column2    0
column3    0
column4    0
dtype: int64